.DEFAULT_GOAL := build-run

report:
	./gradlew jacocoTestReport

run-dist:
	./build/install/app/bin/app file1.json file2.json

clean:
	./gradlew clean

build:
	./gradlew clean build

install:
	./gradlew clean install

run:
	./gradlew run

test:
	./gradlew test

report:
	./gradlew jacocoTestReport

lint:
	./gradlew checkstyleMain checkstyleTest

update-deps:
	./gradlew useLatestVersions

build-run: build run

.PHONY: build
